description "Kindle Reading Records LAN sync service"

start on framework_ready
stop on stopping framework

respawn
respawn limit 5 60
console none

script
    exec /mnt/us/reading-time/bin/reading-syncd >>/mnt/us/reading-time/sync-upstart.log 2>&1
end script
