/* Reading Records v30: hourly chart and compact reading summaries. */
(function(){
"use strict";
var DATA_URL="file:///mnt/us/reading-time/reading-time.tsv";
var SESSIONS_URL="file:///mnt/us/reading-time/reading-sessions.tsv";
var COVERS_URL="file:///mnt/us/reading-time/cover-map.tsv";
var data=[],sessions=[],covers={},tab="today",sortMode="recent",detail={type:null},detailPageIndex=0,booksPageIndex=0,selectedDate=todayKey();
var DETAIL_PAGE_SIZE=8,MONTH_BAR_BASE=36000;
var year=new Date().getFullYear();
function $(id){return document.getElementById(id)}
function pad(n){return n<10?"0"+n:""+n}
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}
function keyDate(y,m,d){return y+"-"+pad(m)+"-"+pad(d)}
function fmt(sec){sec=Math.max(0,parseInt(sec,10)||0);var h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;if(h)return h+"小时"+(m?m+"分钟":"");if(m)return m+"分钟"+(s?"" : "");return s+"秒"}
function fmtShort(sec){sec=Math.max(0,parseInt(sec,10)||0);var h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);if(h)return h+"小时"+(m?m+"分":"");if(m)return m+"分钟";return "0分钟"}
function todayKey(){var d=new Date();return keyDate(d.getFullYear(),d.getMonth()+1,d.getDate())}
function yesterdayKey(){var d=new Date();d.setDate(d.getDate()-1);return keyDate(d.getFullYear(),d.getMonth()+1,d.getDate())}
function shiftDate(key,delta){var p=key.split("-"),d=new Date(parseInt(p[0],10),parseInt(p[1],10)-1,parseInt(p[2],10));d.setDate(d.getDate()+delta);return keyDate(d.getFullYear(),d.getMonth()+1,d.getDate())}
function dateLabel(key){var p=key.split("-"),suffix=key===todayKey()?"（今天）":key===yesterdayKey()?"（昨天）":"";return parseInt(p[1],10)+"月"+parseInt(p[2],10)+"日"+suffix}
function timeSeconds(t){var p=String(t||"").split(":"),h=parseInt(p[0],10)||0,m=parseInt(p[1],10)||0,s=parseInt(p[2],10)||0;return h*3600+m*60+s}
function read(url,cb){var x=new XMLHttpRequest(),done=false,sep=url.indexOf("?")>=0?"&":"?";try{x.onreadystatechange=function(){if(x.readyState===4&&!done){done=true;if(x.status===0||x.status===200)cb(x.responseText,null);else cb(null,"读取失败")}};x.open("GET",url+sep+"fresh="+(new Date().getTime()),true);try{x.setRequestHeader("Cache-Control","no-cache")}catch(ignore){}x.send(null)}catch(e){cb(null,e.message||"读取失败")}}
function parseData(t){var out=[],ls=String(t||"").replace(/\r/g,"").split("\n"),i,p;for(i=0;i<ls.length;i++){if(!ls[i]||/^date\t/.test(ls[i]))continue;p=ls[i].split("\t");if(p.length>=4)out.push({date:p[0],id:p[1],seconds:parseInt(p[2],10)||0,title:p.slice(3).join("\t")||p[1]})}return out}
function parseSessions(t){var out=[],ls=String(t||"").replace(/\r/g,"").split("\n"),i,p;for(i=0;i<ls.length;i++){if(!ls[i]||/^date\t/.test(ls[i]))continue;p=ls[i].split("\t");if(p.length>=5)out.push({date:p[0],start:p[1],end:p[2],id:p[3],title:p.slice(4).join("\t")||p[3]})}return out}
function parseCovers(t){var map={},ls=String(t||"").replace(/\r/g,"").split("\n"),i,p,k;for(i=0;i<ls.length;i++){p=ls[i].split("\t");if(p.length>=2){k=String(p[0]||"").replace(/-/g,"").toUpperCase();if(k)map[k]=p.slice(1).join("\t")}}return map}
function load(cb){read(DATA_URL,function(t,e){if(e){cb(e);return}data=parseData(t);read(SESSIONS_URL,function(s){sessions=parseSessions(s||"");read(COVERS_URL,function(c){covers=parseCovers(c||"");cb(null)})})})}
function rowsDate(d){var a=[],i;for(i=0;i<data.length;i++)if(data[i].date===d)a.push(data[i]);return a}
function rowsMonth(y,m){var p=y+"-"+pad(m),a=[],i;for(i=0;i<data.length;i++)if(data[i].date.indexOf(p)===0)a.push(data[i]);return a}
function sum(a){var s=0,i;for(i=0;i<a.length;i++)s+=a[i].seconds;return s}
function uniqueDays(rows){var o={},i,n=0;for(i=0;i<rows.length;i++)if(!o[rows[i].date]){o[rows[i].date]=1;n++}return n}
function bookAgg(rows){var map={},i,r,k,o,a=[];for(i=0;i<rows.length;i++){r=rows[i];k=r.id||r.title;if(!map[k])map[k]={id:r.id,title:r.title||r.id,seconds:0,lastDate:r.date,lastTime:"",lastStamp:"",count:0};map[k].seconds+=r.seconds;map[k].count++;if(r.date>map[k].lastDate)map[k].lastDate=r.date}
for(i=0;i<sessions.length;i++){r=sessions[i];k=r.id||r.title;if(map[k]){var stamp=(r.date+" "+r.end);if(stamp>map[k].lastStamp){map[k].lastStamp=stamp;map[k].lastDate=r.date;map[k].lastTime=r.end?r.end.substr(0,5):""}}}
for(k in map)if(map.hasOwnProperty(k))a.push(map[k]);return a}
function bookCount(b,dateScope){var c=0,i;for(i=0;i<sessions.length;i++)if(sessions[i].id===b.id&&(!dateScope||sessions[i].date===dateScope))c++;if(c)return c;if(dateScope){for(i=0;i<data.length;i++)if(data[i].id===b.id&&data[i].date===dateScope)return 1;return 0}return b.count}
function sortBooks(a){a=a.slice(0);a.sort(function(x,y){if(sortMode==="total_desc")return y.seconds-x.seconds;if(sortMode==="total_asc")return x.seconds-y.seconds;if(sortMode==="count_desc")return bookCount(y)-bookCount(x)||y.seconds-x.seconds;if(sortMode==="count_asc")return bookCount(x)-bookCount(y)||y.seconds-x.seconds;return y.lastDate.localeCompare(x.lastDate)||y.seconds-x.seconds});return a}
function latestBooks(){return sortBooks(bookAgg(data)).slice(0,5)}
function setTab(t){tab=t;$("mainTabs").className="tabs";$("todayPage").className="page"+(t!=="today"?" hidden":"");$("totalPage").className="page"+(t!=="total"?" hidden":"");$("booksPage").className="page"+(t!=="books"?" hidden":"");$("detailPage").className="page hidden";$("tabToday").className="tab"+(t==="today"?" active":"");$("tabTotal").className="tab"+(t==="total"?" active":"");$("tabBooks").className="tab"+(t==="books"?" active":"");if(t==="today")renderToday();if(t==="total")renderTotal();if(t==="books")renderBooks()}
function hourlyData(d){var a=[],i,r,start,end,cur,next,h;for(i=0;i<24;i++)a[i]=0;for(i=0;i<sessions.length;i++){r=sessions[i];if(r.date!==d)continue;start=timeSeconds(r.start);end=timeSeconds(r.end);if(end<start)end=86400;if(end>86400)end=86400;cur=start;while(cur<end){h=Math.floor(cur/3600);if(h<0||h>23)break;next=Math.min(end,(h+1)*3600);a[h]+=next-cur;cur=next}}return a}
function renderHourlyChart(d){var a=hourlyData(d),h="",i,n,y,left,height,has=false,labels=["12上午","3上午","6上午","9上午","12下午","3下午","6下午","9下午"];for(n=10;n<=60;n+=10){y=254-Math.round(n/60*218);h+='<span class="chart-y-label" style="top:'+(y-9)+'px">'+n+'</span><span class="chart-grid" style="top:'+y+'px"></span>'}for(i=0;i<24;i++){n=Math.min(60,Math.round(a[i]/60));left=7+i*3.85;height=Math.round(n/60*218);if(n)has=true;h+='<span class="hour-bar-slot" style="left:'+left+'%;width:3.45%">'+(n?'<span class="hour-bar-value" style="bottom:'+(height+2)+'px">'+n+'</span><span class="hour-bar" style="height:'+height+'px"></span>':'')+'</span>'}for(i=0;i<8;i++)h+='<span class="chart-x-label" style="left:'+(1+i*11.55)+'%">'+labels[i]+'</span>';if(!has&&sum(rowsDate(d)))h+='<div class="chart-empty">暂无分时记录</div>';$("hourlyChart").innerHTML=h}
function renderToday(){var d=selectedDate,t=sum(rowsDate(d));$("selectedDateLabel").innerHTML=dateLabel(d);$("nextDay").disabled=d>=todayKey();$("todayTotal").innerHTML=fmt(t);renderHourlyChart(d);var books=bookAgg(rowsDate(d)).sort(function(a,b){return b.seconds-a.seconds}),h="";if(!books.length)h='<div class="empty">这一天没有阅读记录</div>';else for(var i=0;i<books.length;i++)h+=bookRow(books[i],d);$("recentList").innerHTML=h;$("updatedAt").innerHTML="数据更新于 "+new Date().getHours()+":"+pad(new Date().getMinutes());}
function lastReadText(b){var d=b.lastDate||"",tm=b.lastTime?(" "+b.lastTime):"";if(d===todayKey())return"今天"+tm;if(d===yesterdayKey())return"昨天"+tm;if(d.length>=10)return d.substr(5,2)+"月"+d.substr(8,2)+"日"+tm;return d+tm}
function coverPath(id){var k=String(id||"").replace(/-/g,"").toUpperCase();return covers[k]||""}
function coverHtml(id,cls){var p=coverPath(id);return p?'<img class="'+cls+'" src="file://'+esc(p)+'" onerror="this.style.display=\'none\'" />':'<span class="book-cover-placeholder"></span>'}
function bookRow(b,dateScope){return '<div class="book-row with-cover-slot" data-id="'+esc(b.id)+'">'+coverHtml(b.id,"book-cover")+'<div class="book-title">'+esc(b.title)+'</div><div class="book-meta">阅读 '+bookCount(b,dateScope)+' 次　·　上次阅读 '+esc(lastReadText(b))+'</div><div class="book-time">'+fmtShort(b.seconds)+'</div><div class="chev">›</div></div>'}
function renderTotal(){var rows=data,y=String(year),yd=[];for(var i=0;i<rows.length;i++)if(rows[i].date.indexOf(y+"-")===0)yd.push(rows[i]);var t=sum(yd),days=uniqueDays(yd),avg=days?Math.floor(t/days):0;$("yearTitle").innerHTML=y+"年 · 月度阅读";$("yearTotal").innerHTML=fmt(t);$("yearSummary").innerHTML=y+"年 · 阅读"+days+"天 · 日均"+fmtShort(avg);var vals=[],max=MONTH_BAR_BASE;for(i=1;i<=12;i++){var s=sum(rowsMonth(year,i));vals.push(s);if(s>max)max=s}var h="";for(i=1;i<=12;i++){var value=vals[i-1],w=value?Math.max(2,Math.round(value/max*100)):0;h+='<div class="month-row" data-month="'+i+'"><span class="month-name">'+pad(i)+'月</span>'+(value?'<span class="month-bar"><span class="month-fill" style="width:'+w+'%;"></span></span>':'')+'<span class="month-value">'+fmtShort(value)+'</span></div>'}$("months").innerHTML=h}
function renderBooks(){var books=sortBooks(bookAgg(data)),h="",b,start=booksPageIndex*12,end=Math.min(books.length,start+12),pages=Math.max(1,Math.ceil(books.length/12));if(booksPageIndex>=pages){booksPageIndex=pages-1;start=booksPageIndex*12;end=Math.min(books.length,start+12)}$("sortLabel").innerHTML=sortText();if(!books.length)h='<div class="empty">还没有阅读记录</div>';else for(var i=start;i<end;i++){b=books[i];h+='<div class="book-row with-cover-slot" data-id="'+esc(b.id)+'">'+coverHtml(b.id,"book-cover")+'<div class="book-title">'+esc(b.title)+'</div><div class="book-meta">上次阅读 '+esc(lastReadText(b))+'　·　阅读 '+bookCount(b)+' 次</div><div class="book-time">'+fmtShort(b.seconds)+'</div><div class="chev">›</div></div>'}$("booksList").innerHTML=h;if(pages>1){$("booksPager").className="pager";$("booksPager").innerHTML='<button data-books-page="prev">上一页</button><span>'+(booksPageIndex+1)+' / '+pages+'</span><button data-books-page="next">下一页</button>'}else{$("booksPager").className="pager hidden";$("booksPager").innerHTML=""}}
function sortText(){if(sortMode==="total_desc")return"总时长↓";if(sortMode==="total_asc")return"总时长↑";if(sortMode==="count_desc")return"次数↓";if(sortMode==="count_asc")return"次数↑";return"最近阅读"}
function monthDetail(y,m){detail={type:"month",y:y,m:m};detailPageIndex=0;showDetail();}
function dayDetail(d){detail={type:"day",date:d};detailPageIndex=0;showDetail();}
function bookDetail(id){detail={type:"book",id:id};detailPageIndex=0;showDetail();}
function pager(total){var pages=Math.max(1,Math.ceil(total/DETAIL_PAGE_SIZE));if(pages<=1)return"";return '<div class="pager"><button data-page="prev">上一页</button><span>'+(detailPageIndex+1)+' / '+pages+'</span><button data-page="next">下一页</button></div>'}
function changeDetailPage(delta,total){var pages=Math.max(1,Math.ceil(total/DETAIL_PAGE_SIZE)),next=detailPageIndex+delta;if(next<0)next=0;if(next>=pages)next=pages-1;if(next!==detailPageIndex){detailPageIndex=next;showDetail()}}
function detailItemCount(){if(detail.type==="book"){var n=0,map={},i;for(i=0;i<data.length;i++)if(data[i].id===detail.id&&!map[data[i].date]){map[data[i].date]=1;n++}return n}return 0}
function showDetail(){$("mainTabs").className="tabs hidden";$("todayPage").className="page hidden";$('totalPage').className="page hidden";$('booksPage').className="page hidden";$('detailPage').className="page";var b=$("detailBody"),h="";
if(detail.type==="month"){var rows=rowsMonth(detail.y,detail.m),total=sum(rows),days=uniqueDays(rows),avg=days?Math.floor(total/days):0,monthBooks=bookAgg(rows).sort(function(a,b){return b.seconds-a.seconds});$("detailTitle").innerHTML=detail.y+"年"+detail.m+"月";h='<div class="summary-block"><div class="summary-total">'+fmt(total)+'</div><div class="summary-meta">阅读'+days+'天 · 日均'+fmtShort(avg)+'</div></div><div class="detail-section">当月阅读书籍</div>';if(!monthBooks.length)h+='<div class="empty">本月没有阅读记录</div>';else for(var mi=0;mi<monthBooks.length;mi++)h+=bookRow(monthBooks[mi],null)}
else if(detail.type==="day"){var rs=rowsDate(detail.date),books=bookAgg(rs).sort(function(a,b){return b.seconds-a.seconds});$("detailTitle").innerHTML=detail.date+(detail.date===todayKey()?"（今天）":"");h='<div class="detail-stat">阅读时长 <b>'+fmt(sum(rs))+'</b></div><div class="detail-stat">阅读书籍数 <b>'+books.length+' 本</b></div><div class="detail-section">阅读书籍</div>';if(!books.length)h+='<div class="empty">这一天没有阅读记录</div>';else for(var j=0;j<books.length;j++)h+=bookRow(books[j],detail.date)}
else {var ba=bookAgg(data),bk=null;for(var q=0;q<ba.length;q++)if(ba[q].id===detail.id){bk=ba[q];break}if(!bk){bk={id:detail.id,title:detail.id,seconds:0,lastDate:"",lastTime:""}}$("detailTitle").innerHTML="书籍详情";h='<div class="book-detail-head'+(coverPath(bk.id)?'':' no-cover')+'">'+coverHtml(bk.id,"book-detail-cover")+'<div class="book-detail-name">'+esc(bk.title)+'</div><div class="book-detail-meta">总阅读 '+fmt(bk.seconds)+'　·　阅读 '+bookCount(bk)+' 次</div><div class="book-detail-meta">最近阅读 '+esc(lastReadText(bk))+'</div></div><div class="detail-section">每日阅读记录</div>';var map={},i;for(i=0;i<data.length;i++)if(data[i].id===bk.id)map[data[i].date]=(map[data[i].date]||0)+data[i].seconds;var keys=[];for(var k in map)if(map.hasOwnProperty(k))keys.push(k);keys.sort().reverse();var bs=detailPageIndex*DETAIL_PAGE_SIZE,be=Math.min(keys.length,bs+DETAIL_PAGE_SIZE);for(i=bs;i<be;i++)h+='<div class="day-row" data-day="'+keys[i]+'">'+keys[i]+'<span class="day-time">'+fmtShort(map[keys[i]])+'</span><span class="chev">›</span></div>';h+=pager(keys.length)}
b.innerHTML=h;}
function closeDetail(){if(detail.type==="month"){setTab("total")}else if(detail.type==="day"){monthDetail(parseInt(detail.date.substr(0,4),10),parseInt(detail.date.substr(5,2),10))}else{setTab("books")}}
function closeApp(){try{if(window.kindle&&kindle.appmgr&&kindle.appmgr.start){kindle.appmgr.start("com.lab126.booklet.home");return}}catch(e){}try{window.close()}catch(e2){}}
function bind(){
function reloadTab(t){load(function(err){if(err){$("message").innerHTML="无法读取阅读数据";return}setTab(t)})}
$("tabToday").onclick=function(){reloadTab("today")};$("tabTotal").onclick=function(){reloadTab("total")};$("tabBooks").onclick=function(){reloadTab("books")};$("todayAll").onclick=function(){reloadTab("books")};
$("prevDay").onclick=function(){selectedDate=shiftDate(selectedDate,-1);renderToday()};$("nextDay").onclick=function(){if(selectedDate<todayKey()){selectedDate=shiftDate(selectedDate,1);renderToday()}};
$("prevYear").onclick=function(){year--;renderTotal()};$("nextYear").onclick=function(){year++;renderTotal()};
$("sortOpen").onclick=function(){$("sortOverlay").className="overlay"};$("sortCancel").onclick=function(){$("sortOverlay").className="overlay hidden"};
var opts=document.getElementsByClassName("sort-option"),i;for(i=0;i<opts.length;i++)opts[i].onclick=function(){sortMode=this.getAttribute("data-sort");booksPageIndex=0;$("sortOverlay").className="overlay hidden";renderBooks()};
$("detailBack").onclick=closeDetail;
$("months").onclick=function(e){var t=e.target;while(t&&t.getAttribute&&t.getAttribute("data-month")===null)t=t.parentNode;if(t&&t.getAttribute){monthDetail(year,parseInt(t.getAttribute("data-month"),10))}};
$("recentList").onclick=function(e){var t=e.target;while(t&&t.getAttribute&&t.getAttribute("data-id")===null)t=t.parentNode;if(t&&t.getAttribute)bookDetail(t.getAttribute("data-id"))};
$("booksList").onclick=function(e){var t=e.target;while(t&&t.getAttribute&&t.getAttribute("data-id")===null)t=t.parentNode;if(t&&t.getAttribute)bookDetail(t.getAttribute("data-id"))};
$("booksPager").onclick=function(e){var t=e.target,dir=t&&t.getAttribute?t.getAttribute("data-books-page"):null;if(!dir)return;var total=bookAgg(data).length,pages=Math.max(1,Math.ceil(total/12));if(dir==="next"&&booksPageIndex<pages-1)booksPageIndex++;if(dir==="prev"&&booksPageIndex>0)booksPageIndex--;renderBooks()};
$("detailBody").onclick=function(e){var t=e.target;while(t&&t.getAttribute&&t.getAttribute("data-day")===null&&t.getAttribute("data-id")===null&&t.getAttribute("data-page")===null)t=t.parentNode;if(t&&t.getAttribute){if(t.getAttribute("data-page"))changeDetailPage(t.getAttribute("data-page")==="next"?1:-1,detailItemCount());else if(t.getAttribute("data-day"))dayDetail(t.getAttribute("data-day"));else if(t.getAttribute("data-id"))bookDetail(t.getAttribute("data-id"))}};
if(window.kindle&&kindle.appmgr)kindle.appmgr.onback=function(){if($("detailPage").className.indexOf("hidden")<0)closeDetail();else closeApp()};
if(window.kindle&&kindle.gestures)kindle.gestures.onswipe=function(direction){if($("detailPage").className.indexOf("hidden")<0){if(direction==="up"||direction==="north")changeDetailPage(1,detailItemCount());if(direction==="down"||direction==="south")changeDetailPage(-1,detailItemCount())}else if(tab==="books"){if(direction==="up"||direction==="north")$("booksPage").scrollTop+=500;if(direction==="down"||direction==="south")$("booksPage").scrollTop=Math.max(0,$("booksPage").scrollTop-500)}};
var touchY=null;$("detailBody").ontouchstart=function(e){if(e.touches&&e.touches.length)touchY=e.touches[0].clientY};$("detailBody").ontouchend=function(e){if(touchY===null)return;var y=(e.changedTouches&&e.changedTouches.length)?e.changedTouches[0].clientY:touchY,delta=touchY-y;touchY=null;if(Math.abs(delta)>30)changeDetailPage(delta>0?1:-1,detailItemCount())};
var booksTouchY=null;$("booksPage").ontouchstart=function(e){if(e.touches&&e.touches.length)booksTouchY=e.touches[0].clientY};$("booksPage").ontouchend=function(e){if(booksTouchY===null)return;var y=(e.changedTouches&&e.changedTouches.length)?e.changedTouches[0].clientY:booksTouchY,delta=booksTouchY-y;booksTouchY=null;if(Math.abs(delta)>30)$("booksPage").scrollTop=Math.max(0,$("booksPage").scrollTop+(delta>0?500:-500))};
}
function init(){bind();load(function(err){if(err){$("message").innerHTML="无法读取阅读数据";return}renderToday()})}
if(document.readyState==="complete"||document.readyState==="interactive")init();else document.addEventListener("DOMContentLoaded",init,false);
})();
